import cognitive_processes_learning_theories_aspects_foundation_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace cognitive_processes_learning_theories_aspects_foundation_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end cognitive_processes_learning_theories_aspects_foundation_canonical_lane_mathlib
end HautevilleHouse
